# init react app
ui-init: ui-install ui-build
ui-build: ui-build-app

# install react
ui-setup:
	${DC} ${COMPOSE_FILES} exec -T node /bin/sh -c "cd .. && mkdir tmp && cd tmp && yarn create vite react --template react && cp -r ./react/* ../react/"

# install react-ts
ui-setup-ts:
	${DC} ${COMPOSE_FILES} exec -T node /bin/sh -c "cd .. && mkdir tmp && cd tmp && yarn create vite react --template react-ts && cp -r ./react/* ../react/"

# install next
next-setup:
	${DC} ${COMPOSE_FILES} exec -T node /bin/sh -c "cd .. && mkdir tmp && cd tmp && yarn create next-app next --js --eslint && cp -r ./next/* ../next/"


# install frontend dependencies
ui-install:
	${DC} ${COMPOSE_FILES} exec -T node /bin/sh -c "yarn"

# run test suite
ui-test:
	${DC} ${COMPOSE_FILES} exec node /bin/sh -c "yarn test"

# build application
ui-build-app:
	${DC} ${COMPOSE_FILES} exec node /bin/sh -c "yarn build"

# start react dev server
ui-dev:
	${DC} ${COMPOSE_FILES} exec node /bin/sh -c "yarn run dev"


# add npm package
ui-add:
	@read -p "NPM Package? : " TAG \
	&& ${DC} ${COMPOSE_FILES} exec node /bin/sh -c "yarn add $${TAG}"

ui-localsetup:
	${DC} ${COMPOSE_FILES} exec -T node /bin/sh -c "mkdir -p /home/node/react/src/utils && cp -a /setup/getApiData.js /home/node/react/src/utils && cp -a /setup/.vscode /home/node/react"
	${DC} ${COMPOSE_FILES} exec -T node /bin/sh -c "echo VITE_API_URL=//cms.${NAME}.local >> /home/node/react/.env"
	${DC} ${COMPOSE_FILES} exec -T node /bin/sh -c "echo VITE_API_URL=//cms.${NAME}.local >> /home/node/react/.env.local"

next-localsetup:
	${DC} ${COMPOSE_FILES} exec -T node /bin/sh -c "mkdir -p /home/node/next/src/utils && cp -a /setup/getApiData.js /home/node/next/src/utils && cp -a /setup/.vscode /home/node/next"

