cms-fix:
	make stop && sudo rm -rf apps/strapi/node_modules && make up
	
# add npm package
cms-add:
	@read -p "NPM Package? : " TAG \
	&& ${DC} ${COMPOSE_FILES} exec strapi /bin/sh -c "cd /app/strapi && yarn add $${TAG}"	