  node:
    image: node:fermium-slim
    container_name: ${COMPOSE_PROJECT_NAME}_node
    mem_limit: 2G
    working_dir: /home/node/next    
    command: sh -c 'tail -f /dev/null'
    ports:
      - 3000:3000
    volumes:
      - ../apps/next:/home/node/next
      - ../setup/react:/setup
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_node.rule=Host(`dev.${COMPOSE_PROJECT_NAME}.local`)

  next:
    image: nginx:1.20.1-alpine
    hostname: next
    container_name: ${COMPOSE_PROJECT_NAME}_next
    volumes:
      - ../apps/react/dist:/usr/share/nginx/html
      - ../setup/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      vpcbr:
        ipv4_address: 10.1.10.5
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_next.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_next.rule=Host(`www.${COMPOSE_PROJECT_NAME}.local`,`${COMPOSE_PROJECT_NAME}.local`)

