  node:
    image: node:fermium-slim
    container_name: ${COMPOSE_PROJECT_NAME}_node
    mem_limit: 2G
    environment:  
      VITE_SERVER_PORT: "3003"
    working_dir: /home/node/app    
    command: sh -c 'tail -f /dev/null'
    ports:
      - 3003:3003
    volumes:
      - ../apps/react:/home/node/app
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_node.rule=Host(`dev.${COMPOSE_PROJECT_NAME}.local`)

  react:
    image: nginx:1.20.1-alpine
    hostname: react
    container_name: ${COMPOSE_PROJECT_NAME}_react
    volumes:
      - ../apps/react/dist:/usr/share/nginx/html
      - ../setup/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      vpcbr:
        ipv4_address: 10.1.0.5
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_react.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_react.rule=Host(`www.${COMPOSE_PROJECT_NAME}.local`,`${COMPOSE_PROJECT_NAME}.local`)