  strapi:
    container_name: ${COMPOSE_PROJECT_NAME}_strapi4
    image: node:fermium-slim
    working_dir: /srv 
    command: sh -c "chmod +x /srv/run/develop.sh && exec /srv/run/develop.sh"
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ../apps/strapi:/app/strapi
      - ../setup/strapi/dbconfig:/srv/config
      - ../setup/strapi/run:/srv/run
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.1.10.3
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_strapi.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_strapi.rule=Host(`cms.${COMPOSE_PROJECT_NAME}.local`)        

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ../apps/mariadb:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 10.1.10.4      
