cms-install:
	${DC} ${COMPOSE_FILES} exec -T strapi /bin/sh -c "yarn add @strapi/strapi && cd ./node_modules/@strapi/strapi/bin && node ./strapi.js new strapi --dbclient=mysql --dbhost=127.0.0.1 --dbport=3306 --dbname=strapi --dbusername=strapi --dbpassword=strapi --dbforce && cp -a ./strapi/. /app/strapi/ && cd /app/strapi && yarn install && yarn build"

cms-fix:
	make stop && sudo rm -rf apps/strapi/node_modules && make up

cms-reinit:
	make up db-restore && ${DC} ${COMPOSE_FILES} exec -T strapi /bin/sh -c "cd /app/strapi && rm -rf ./node_modules && yarn install && yarn build" && make up